### ISSUE TITLE
这个其实应该也符合?

### ISSUE THREAD

**Issue by DragonQuestHero** [ExpLife/awesome-windows-kernel-security-development#2]
上次翻了一下你Profile..发现是国人..
https://github.com/stonedreamforest/re_avkmgr
https://github.com/stonedreamforest/re_sysdiag
都是逆向还原的项目 其实蛮不错的

**Comment by DragonQuestHero** [comment]
https://github.com/KhaiTB/BKAV.Filter
这个项目404了 你验证一下

**Comment by ExpLife** [comment]
see  https://github.com/ExpLife/BKAV.Filter




------------------ 原始邮件 ------------------
发件人: "DragonQuestHero"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:20
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)




https://github.com/KhaiTB/BKAV.Filter
 这个项目404了 你验证一下

**Comment by LiDogEggA** [comment]
是404了, 请问你是?




------------------ 原始邮件 ------------------
发件人: "DragonQuestHero"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:20
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)




https://github.com/KhaiTB/BKAV.Filter
 这个项目404了 你验证一下

**Comment by ExpLife** [comment]
https://github.com/stonedreamforest/re_avkmgr
https://github.com/stonedreamforest/re_sysdiag  
这两个看我的仓库 里面以前有fork

我中文ID:安于此生 英文ID:ExpLife

**Comment by LiDogEggA** [comment]
卧槽, 原来是师兄, 感谢!~


------------------ 原始邮件 ------------------
发件人: "ExpLife"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:25
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "Mr.kong"<332142270@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)




https://github.com/stonedreamforest/re_avkmgr
 https://github.com/stonedreamforest/re_sysdiag
 这两个看我的仓库 里面以前有fork
 
我中文ID:安于此生 英文ID:ExpLife

**Comment by ExpLife** [comment]
厉害了,你几期的?




------------------ 原始邮件 ------------------
发件人: "LiDogEggA"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:28
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)



卧槽, 原来是师兄, 感谢!~ 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "ExpLife"<notifications@github.com>; 
 发送时间: 2018年3月5日(星期一) 下午4:25 
 收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>; 
 抄送: "Mr.kong"<332142270@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2) 
 
 
 
 
 https://github.com/stonedreamforest/re_avkmgr 
  https://github.com/stonedreamforest/re_sysdiag 
  这两个看我的仓库 里面以前有fork 
   
 我中文ID:安于此生 英文ID:ExpLife

**Comment by LiDogEggA** [comment]
25期 孔帅, 久仰大名, 哈哈哈哈




------------------ 原始邮件 ------------------
发件人: "ExpLife"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:30
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "Mr.kong"<332142270@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)



厉害了,你几期的? 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "LiDogEggA"<notifications@github.com>; 
 发送时间: 2018年3月5日(星期一) 下午4:28 
 收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>; 
 抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2) 
 
 
 
 卧槽, 原来是师兄, 感谢!~  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "ExpLife"<notifications@github.com>;  
  发送时间: 2018年3月5日(星期一) 下午4:25  
  收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;  
  抄送: "Mr.kong"<332142270@qq.com>; "Comment"<comment@noreply.github.com>;   
  主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)  
   
   
   
   
  https://github.com/stonedreamforest/re_avkmgr  
   https://github.com/stonedreamforest/re_sysdiag  
   这两个看我的仓库 里面以前有fork  
     
  我中文ID:安于此生 英文ID:ExpLife

**Comment by ExpLife** [comment]
222333


------------------ 原始邮件 ------------------
发件人: "LiDogEggA"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:31
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)



25期 孔帅, 久仰大名, 哈哈哈哈 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "ExpLife"<notifications@github.com>; 
 发送时间: 2018年3月5日(星期一) 下午4:30 
 收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>; 
 抄送: "Mr.kong"<332142270@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2) 
 
 
 
 厉害了,你几期的?  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "LiDogEggA"<notifications@github.com>;  
  发送时间: 2018年3月5日(星期一) 下午4:28  
  收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;  
  抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>;   
  主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)  
   
   
   
  卧槽, 原来是师兄, 感谢!~   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "ExpLife"<notifications@github.com>;   
   发送时间: 2018年3月5日(星期一) 下午4:25   
   收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;   
   抄送: "Mr.kong"<332142270@qq.com>; "Comment"<comment@noreply.github.com>;    
   主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)   
     
     
     
     
   https://github.com/stonedreamforest/re_avkmgr   
    https://github.com/stonedreamforest/re_sysdiag   
    这两个看我的仓库 里面以前有fork   
       
   我中文ID:安于此生 英文ID:ExpLife

**Comment by DragonQuestHero** [comment]
https://github.com/aleksk/LazyCopy
微过滤里面这个重复了2次

**Comment by DragonQuestHero** [comment]
标注下作者重新放上去把 我只是偶然点到了 发现404 
话说你们期是什么鬼?培训班?大学?

**Comment by DragonQuestHero** [comment]
那两个逆向的我的意思是感觉不错 也可以考虑加入这个列表

**Comment by ExpLife** [comment]
恩,我加一下


------------------ 原始邮件 ------------------
发件人: "DragonQuestHero"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:36
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)




那两个逆向的我的意思是感觉不错 也可以考虑加入这个列表

**Comment by DragonQuestHero** [comment]
刚看雪搜了一下 看到你了 不好意思 很少逛

**Comment by ExpLife** [comment]
加好了




------------------ 原始邮件 ------------------
发件人: "DragonQuestHero"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:39
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)




Closed #2.

**Comment by ExpLife** [comment]
我这两年也很少逛




------------------ 原始邮件 ------------------
发件人: "DragonQuestHero"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:39
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)




刚看雪搜了一下 看到你了 不好意思 很少逛

**Comment by DragonQuestHero** [comment]
那个重复的也记得删一下
其实我也想逛 但是没时间...不说了 待会他们看一下我github动态一看我在聊天就GG了

**Comment by ExpLife** [comment]
重复的已经删好了 




------------------ 原始邮件 ------------------
发件人: "DragonQuestHero"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 下午4:42
收件人: "ExpLife/awesome-windows-kernel-security-development"<awesome-windows-kernel-security-development@noreply.github.com>;
抄送: "熊冰心"<957493575@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ExpLife/awesome-windows-kernel-security-development] 这个其实应该也符合? (#2)




那个重复的也记得删一下
 其实我也想逛 但是没时间...不说了 待会他们看一下我github动态一看我在聊天就GG了
