### ISSUE TITLE
我手里还有几个

### ISSUE THREAD

**Issue by DragonQuestHero** [ExpLife/awesome-windows-kernel-security-development#4]
https://github.com/majdi/deadlands
这个其实挺有意思的 不过win平台的得自己翻一下https://github.com/d30sa1/RootKits-List-Download
还有一些好low说是隐藏进程进去一看是个dll注入 一点技术含量都没有
方便留个企鹅交流?processhacker@163.com

**Comment by ExpLife** [comment]
https://github.com/majdi/deadlands,https://github.com/d30sa1/RootKits-List-Download  

这个list我之前fork过,前面一个例子比较简单  

码云我也有账号

**Comment by DragonQuestHero** [comment]
VwFirewall 这个东西还是可以的 可惜在码云 不知道能不能随便搬
这个怎么说也是成熟产品 现在开源

**Comment by ExpLife** [comment]
恩 VwFirewall可以 XP版的
